lang: ruby
before_script:
  # workaround to fix rake not found
  - gem install rake
deploy:
  provider: s3
  access_key_id: AKIAJI5IEZIZRL3U74JQ
  secret_access_key:
    secure: q3cAHEWbCkHexHV5/HF78zD/mTeFpKEfmv9huTLSvNALOgeUkNCwW3aqS+/XyiG+RZlRsRt1+jqzQP3OospJEeG4YatnotqWv/iXZHE8kIqxI92zC11veebC6LX4HFcwAaNdSWc2rNdaf+Wct+NAZO4jwZEK1DFvRpCvrheNA/99QE6N0Sda7gSqbZPYHP2j9f2tobfCwtmlSL3ssj85OjIl39GMYpLg+jRPZ+39MkW9Kehgr6Kt8jnWMfhqykdMhCm12ES7Dpk7ASa7QOgzKm2ixzGFks6ERkUxXD+R66ne+vNGv4PrLgkKEnVOBXXgcGelDSd0B9ka2msZ/mQGYST8HlRJIU0afX1hitQVTr4dcqKkGJgI983+iDpmWZI1lLDwD0yinz1oKwYxme4/P4zPTJrvOB0Z9q/6dF2K2jvG43oMXj2NDhxRDGC69o7ruhvsmntzSvOHrepTJtnZFjp1qVTHwgiZixNJwCChSWenLpp8iSd6j4fDnR4VrYOFztORZDRmYJxw0nlSX6DZKXrFyT8uh5vmSJWtIk0lTd3O/1joHy4dbU2kW0xfKYN2HKFOtHYEgghsVTh2h1nSdC5E3eB2A9hrWPQd1uP4ZRMVjTaDQyICPy7emrc08D4XJTfoG768iqT9PXLzz4WoQlFNVulm2wONPepY9P+gmaA=
  bucket: adivinhe-site
  skip_cleanup: true
  acl: public_read
