deploy:
  provider: s3
  access_key_id: AKIAJI5IEZIZRL3U74JQ
  secret_access_key:
    secure: Nkh0gxgoGYAv5jvIzqItni0zRmBCL0oSMHLw1fS/MrdB99vZLZKjHeRERghbdkrmR0SfGjsV1iVJdXSQKfkmeI6lphiwKkxH1Ld/hYpu4tj7h9wF//rQCCw5/Dvnyr1xTr+x7F1b4IEQ8v3vlIoNTKdclVfNOKSAoQ3x7MnmZgdUFduwjeDYk8sWFuc6fzZIoaqzG2vuGgppl90yAW4qSI6g3TI7aryXH1jtTJ8JttDaMZoo70/pvswBKlB4vzEOJZX5zpKhOYnIW3b7CwyOh/ffGgkQL8sx8MSOMt98BpwkBkKFU+rMzZq7neZFyBAGBSszi2mIpRY5VOxLZUgt8V47uYFoLFdeWka+72AstpjlEMdF7TXp9zD6PTbZLPyB41oc53Y469aofo80lKtkssixs1O6PrjX+2rGv8tg7ue9IXyoHmcIcS8M5oNgDnWYdnr4ra2P/oqFSEd+YB63bVBTdY5QqS6FIY3B6IL+wlSC5mpGX/2fY3OMbHnvGkZyU4Nti8DUo3aDq6MGXfshBBXB3CqSj84Kobwx/q3XWjqtB6kvKjUUDEyblzyj8AkKw1752lw63YRez2cKm9gDITNsNrsxS0E9hhQqhwK8441JbWO/T33bsVdIpAdOKv0vG/e3hZgTvfe8CGiAKKzw5QLBKjSpZ0BH1GY/qTrBrH0=
  bucket: adivinhe-site
  skip_cleanup: true
  acl: public_read
