lang: ruby
before_script:
- gem install rake
deploy:
  provider: s3
  access_key_id: AKIAJACYA6LZV4F4T7ZA
  secret_access_key:
    secure: GepjwIPSeRcAWzzM0zkqfiH7xrVxG39Sa69LlV6oyMOEA9ThLVPtZ4RVw//e+v8qVwipC8k2E1bGjfi9+f+1OScYcJQgfC1pxAk8aHfZbOMkZ9jRs2lk2UEmT8TbvYkGc2CDUE8aHst8tT4ux6Aspxbmw9Nvu5+PCFzwdygF4HdP6EcmfR5vodEJPiE5TQ2Daoa3a7fISwgezryEkRQtEkd9h8xDRtaw5LhkbTnLPMrs3tDoWQWS97VIV4sADHVkRgOkbfozfqzusbmnWfimmkR6enhRnQng4c3YBstlf2gM9znYuHuiSiu6m70EnGJq0KcZw6TXHdnanmsheGOFsF1SrrYVZSr9bpt9ZPJcUX2xCxADBqSmJ53Gv+91LozFQvAymolGpzGFsxYXbD9UrUpvs+zqyx1S1Pw8zEWxT38vxSX7FDmguxG6TS2/TJPiQK+AesMWSdQS+7MAU3Sl+8fWZFQvDAcfdRtJBSccu6hzqUeuYwJVjP2fI3XQtVH3SQ1DDHmAyhVUNaymGF9GjNCUvgAhLYehzenmh7DILDRG+eysgEgo1mfvwcjyJTWbEAUKyE8OIgPDVXr1B/otsAtzHLN+9P9eZCBXfsAhsPLI8OX6lp1BhQIihSQIh7ON03Gey34EH9UhGC9SqFSTasQeXgeeh/+5bb5866/LXxc=
  bucket: adivinhe-site
  skip_cleanup: true
  acl: public_read
